services:
  db:
    image: mariadb:12.2.2
    container_name: pagos_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: streaming
      MARIADB_USER: nava
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: pagos_app
    restart: unless-stopped  # <--- Añade esto aquí también
    volumes:
      # - .:/app
      # - ./storage:/app/storage
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - ./rclone.conf:/root/.config/rclone/rclone.conf:ro
      - .:/app:Z
      - ./storage:/app/storage:Z
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      db: # Versión extendida para evitar el error de conexión que vimos antes
        condition: service_started

volumes:
  db_data: